name: flutter_application_2
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  vibration: ^1.8.1
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  vector_math: ^2.1.0 # ベクトル計算用のパッケージ



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/water.jpg
    - assets/images/seikai.png
    - assets/images/fuseikai.png
    - assets/images/icon.png
    - assets/images/hit.png