// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEO8Bq1qz6rXWB_7L0N6FIRoRGtwCn8Qc',
    appId: '1:673907129441:web:c7433f965d12f0dec07e20',
    messagingSenderId: '673907129441',
    projectId: 'fir-test-caefe',
    authDomain: 'fir-test-caefe.firebaseapp.com',
    storageBucket: 'fir-test-caefe.appspot.com',
    measurementId: 'G-ZJVN23GC1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_RDXe1kY_557W6fQDHJcilcZ2CZY3Oc',
    appId: '1:673907129441:android:58ae2d75d6e3f2d2c07e20',
    messagingSenderId: '673907129441',
    projectId: 'fir-test-caefe',
    storageBucket: 'fir-test-caefe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_eKsIF2t4duqyWk2hLP_FkN0A8S2RHLI',
    appId: '1:673907129441:ios:440120df4a92aadac07e20',
    messagingSenderId: '673907129441',
    projectId: 'fir-test-caefe',
    storageBucket: 'fir-test-caefe.appspot.com',
    iosClientId: '673907129441-1piru15k6tfqdv2tm3phl6hei1vuvbp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_eKsIF2t4duqyWk2hLP_FkN0A8S2RHLI',
    appId: '1:673907129441:ios:e58aad10493b9cffc07e20',
    messagingSenderId: '673907129441',
    projectId: 'fir-test-caefe',
    storageBucket: 'fir-test-caefe.appspot.com',
    iosClientId: '673907129441-qk6so5p29sm76lsjr97ge5tea74armv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
